-- ============================================================
-- Migration : FAQ bilingue FR/EN + clé unique (slug, langue)
-- À exécuter sur une base déjà installée (le schema.sql complet
-- contient déjà ces définitions pour les nouvelles installations)
-- ============================================================

-- 1) Un même slug peut exister dans plusieurs langues
ALTER TABLE `pages` DROP INDEX `slug`, ADD UNIQUE KEY `uniq_slug_lang` (`slug`, `language_code`);

-- 2) Normalise l'ancien slug anglais
UPDATE `pages` SET `slug` = 'faq' WHERE `slug` = 'faq-en';

-- 3) Contenu français
UPDATE `pages` SET
  `title` = 'FAQ — Comment ça marche ?',
  `meta_title` = 'FAQ — Comment fonctionne l''échange de liens ?',
  `meta_description` = 'Comment fonctionne l''échange de liens ? Gagnez des points, boostez votre classement et parrainez vos amis : toutes les réponses pour bien démarrer.',
  `content` = '<h2>Tout savoir pour bien démarrer et gagner du trafic</h2><p>Vous vous demandez comment fonctionne notre plateforme d''échange de liens ? Cette FAQ vous explique tout, pas à pas, pour transformer vos visites en points et vos points en trafic réel vers votre site.</p><h3>1. Qu''est-ce que l''échange de liens ?</h3><p>C''est simple : vous visitez les sites des autres membres, et en échange votre propre site reçoit des visites. Chaque visite validée vous rapporte des points, et ce sont ces points qui propulsent votre lien en tête du classement.</p><h3>2. Comment gagner des points ?</h3><ul><li><strong>Visitez des liens</strong> : chaque visite validée (quelques secondes sur le site) crédite des points sur votre compte.</li><li><strong>Page Bonus</strong> : des bannières rémunérées vous offrent 5 points supplémentaires par visite de 15 secondes.</li><li><strong>Parrainage</strong> : partagez votre lien de parrainage et gagnez 1 point par visite unique (1 par IP toutes les 24 h), plus un bonus de 1000 points à l''inscription de chaque filleul.</li></ul><h3>3. Comment propulser mon lien dans le classement ?</h3><p>Ajoutez votre lien depuis votre tableau de bord, puis attribuez-lui une partie de vos points. Plus un lien accumule de points, plus il monte dans le classement et plus il est vu et visité par la communauté.</p><h3>4. Comment acheter des points VIP ?</h3><p>Depuis la section VIP de votre tableau de bord, via PayPal ou en cryptomonnaies. Les points sont crédités après confirmation du paiement par l''administrateur.</p><h3>5. Est-ce vraiment gratuit ?</h3><p>Oui, à 100 %. L''inscription et toutes les fonctionnalités de base sont gratuites. Les packs VIP, facultatifs, permettent simplement d''acheter des points supplémentaires et de soutenir le site.</p><h3>6. Est-ce sécurisé ?</h3><p>Oui. Les visites passent par une visionneuse intégrée, l''auto-visite est bloquée par notre système anti-fraude, les liens abusifs sont signalables puis blacklistés, et vos données sont protégées (mot de passe chiffré, connexion sécurisée).</p><h3>7. Comment commencer ?</h3><ol><li>Créez votre compte gratuit en 30 secondes.</li><li>Ajoutez votre premier lien.</li><li>Visitez quelques sites pour gagner vos premiers points.</li><li>Attribuez vos points à votre lien et regardez-le grimper !</li></ol><p><a href="register"><strong>Créer mon compte gratuitement et gagner mes premiers points →</strong></a></p>'
WHERE `slug` = 'faq' AND `language_code` = 'fr';

-- 4) Contenu anglais
UPDATE `pages` SET
  `title` = 'FAQ — How does it work?',
  `meta_title` = 'FAQ — How does link exchange work?',
  `meta_description` = 'How does link exchange work? Earn points, climb the ranking and refer friends: every answer you need to get started.',
  `content` = '<h2>Everything you need to start earning traffic</h2><p>Wondering how our link exchange platform works? This FAQ walks you through everything, step by step, so you can turn your visits into points and your points into real traffic for your website.</p><h3>1. What is link exchange?</h3><p>It''s simple: you visit other members'' websites, and in return your own website receives visits. Every validated visit earns you points, and those points push your link to the top of the ranking.</p><h3>2. How do I earn points?</h3><ul><li><strong>Visit links</strong>: every validated visit (a few seconds on the site) credits points to your account.</li><li><strong>Bonus page</strong>: rewarded banners give you 5 extra points per 15-second visit.</li><li><strong>Referrals</strong>: share your referral link and earn 1 point per unique visit (1 per IP every 24 h), plus a 1000-point bonus when each referred user signs up.</li></ul><h3>3. How do I boost my link in the ranking?</h3><p>Add your link from your dashboard, then assign part of your points to it. The more points a link collects, the higher it climbs and the more it gets seen and visited by the community.</p><h3>4. How do I buy VIP points?</h3><p>From the VIP section of your dashboard, via PayPal or cryptocurrency. Points are credited after the payment is confirmed by the administrator.</p><h3>5. Is it really free?</h3><p>Yes, 100% free. Registration and all core features cost nothing. Optional VIP packs simply let you buy extra points and support the site.</p><h3>6. Is it safe?</h3><p>Yes. Visits run through an integrated viewer, self-visiting is blocked by our anti-fraud system, abusive links can be reported and are blacklisted, and your data is protected (hashed passwords, secure connection).</p><h3>7. How do I get started?</h3><ol><li>Create your free account in 30 seconds.</li><li>Add your first link.</li><li>Visit a few sites to earn your first points.</li><li>Assign points to your link and watch it climb!</li></ol><p><a href="register"><strong>Create my free account and earn my first points →</strong></a></p>'
WHERE `slug` = 'faq' AND `language_code` = 'en';
